version: '3'

services:
  server:
    container_name: API_PRODUCTS
    build: '.'
    volumes:
      - ./:/node-app
    depends_on:
      - db
    links:
      - db
    ports:
      - '3000:3000'

  db:
    image: 'mongo'
    container_name: MONGODB_PRODUCTS
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db